kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ingress-controller
  namespace: default
data:
  http-snippet: "load_module /datadog_mount/ngx_http_datadog_module.so;"
  location-snippet: |
    datadog_rum_version "5";
    datadog_rum_config "applicationId" "<DATADOG_APPLICATION_ID>";
    datadog_rum_config "clientToken" "<DATADOG_CLIENT_TOKEN>";
    datadog_rum_config "site" "datadoghq.com";
    datadog_rum_config "service" "my-web-application";
    datadog_rum_config "env" "production";
    datadog_rum_config "version" "1.0.0";
    datadog_rum_config "sessionSampleRate" "100";
    datadog_rum_config "sessionReplaySampleRate" "100";
    datadog_rum_config "trackResources" "true";
    datadog_rum_config "trackLongTasks" "true";
    datadog_rum_config "trackUserInteractions" "true";
